import React from 'react';
import HeadingTextAlt from './Styles/HeadingTextAlt';

const PrivacyPolicy = () => {
    return (
        <div className="container mx-auto p-4 text-white space-y-8">
            <div className="flex items-center justify-center">
                <HeadingTextAlt title={'PRIVACY POLICY'} titleSize='text-2xl' subtitle={'LAST UPDATED: SEPTEMBER 18, 2024'}  subtitleSize='md:text-xl text-base'  minWidth='md:min-w-[50px] min-w-[35px]'/>
            </div>

            <p className="leading-relaxed">
                This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>

            <p className="leading-relaxed">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.privacypolicies.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer" className="text-dark-main underline">Privacy Policy Generator</a>.
            </p>

            <section>
                <h2 className="text-2xl font-semibold mt-8 mb-4 scale-y-125">INTERPRETATION AND DEFINITIONS</h2>
                <h3 className="text-xl font-semibold mb-2 scale-y-125">INTERPRETATION</h3>
                <p className="leading-relaxed">
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
                <h3 className="text-xl font-semibold mt-4 mb-2 scale-y-125">DEFINITIONS</h3>
                <p className="leading-relaxed mb-4">For the purposes of this Privacy Policy:</p>
                <ul className="list-disc list-inside space-y-2">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party...</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Barber Shop.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device...</li>
                    <li><strong>Country</strong> refers to: United Kingdom.</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company...</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service...</li>
                    <li><strong>Website</strong> refers to Barber Shop, accessible from <a href="https://juxtaj.com/barbershopbooking" target="_blank" rel="external nofollow noopener noreferrer" className="text-dark-main underline">https://juxtaj.com/barbershopbooking</a>
                    </li>
                    <li><strong>You</strong> means the individual accessing or using the Service...</li>
                </ul>
            </section>

            <section>
                <h2 className="text-2xl font-semibold mt-8 mb-4">COLLECTING AND USING YOUR PERSONAL DATA</h2>
                <h3 className="text-xl font-semibold mb-2 scale-y-125">TYPES OF DATA COLLECTED</h3>
                <h4 className="text-lg font-semibold mb-2 scale-y-125">PERSONAL DATA</h4>
                <p className="leading-relaxed">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You...
                </p>
                <ul className="list-disc list-inside space-y-2">
                    <li>Email address</li>
                    <li>Phone number</li>
                    <li>Usage Data</li>
                </ul>
            </section>

            <section>
                <h3 className="text-xl font-semibold mt-8 mb-4 scale-y-125">USE OF YOUR PERSONAL DATA</h3>
                <p className="leading-relaxed">
                    The Company may use Personal Data for the following purposes:
                </p>
                <ul className="list-disc list-inside space-y-2">
                    <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account</strong>: to manage Your registration as a user of the Service...</li>
                    <li><strong>For the performance of a contract</strong>: the development, compliance and undertaking...</li>
                    <li><strong>To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication...</li>
                    <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services, and events...</li>
                    <li><strong>To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
                </ul>
            </section>

            <section>
                <h2 className="text-2xl font-semibold mt-8 mb-4 scale-y-125">CONTACT US</h2>
                <p className="leading-relaxed">
                    If you have any questions about this Privacy Policy, You can contact us:
                </p>
                <ul className="list-disc list-inside">
                    <li>By email: <a href="mailto:josh@juxtaj.com" className="text-dark-main underline">josh@juxtaj.com</a></li>
                </ul>
            </section>
        </div>
    );
}

export default PrivacyPolicy;
